version: "2"
linters:
  enable:
    - gosec
    - misspell
    - revive
    - whitespace
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
